"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
******************************************************************************************
This protocol is UNSTABLE in the sense of being subject to change.
******************************************************************************************
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _StreamsError:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StreamsErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_StreamsError.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    STREAMS_ERROR_UNSPECIFIED: _StreamsError.ValueType  # 0
    """Default value. This value is not used.
    An error code MUST always be set to a non-zero value.
    If an error code is not explicitly set, it MUST be treated as
    an internal server error (INTERNAL).
    """
    STREAMS_ERROR_STREAM_NOT_FOUND: _StreamsError.ValueType  # 1
    """The requested stream does not exist in the database.

    Common causes:
    - Stream name typo or incorrect stream identifier
    - Stream was never created (no events appended yet)
    - Stream was deleted and not yet recreated

    Client action: Verify the stream name is correct. Create the stream by appending to it.
    Recoverable by creating the stream first (append with NO_STREAM expected revision).
    """
    STREAMS_ERROR_STREAM_ALREADY_EXISTS: _StreamsError.ValueType  # 2
    """The stream already exists when an operation expected it not to exist.

    Common causes:
    - Attempting to create a stream that already has events
    - Using NO_STREAM expected revision on an existing stream
    - Race condition with concurrent stream creation

    Client action: Use the existing stream or use a different expected revision.
    Recoverable by adjusting the expected revision or using the existing stream.
    """
    STREAMS_ERROR_STREAM_DELETED: _StreamsError.ValueType  # 3
    """The stream has been soft deleted.
    Soft-deleted streams are hidden from stream lists but can be restored by appending to them.

    Common causes:
    - Stream was explicitly soft-deleted via delete operation
    - Attempting to read from a soft-deleted stream

    Client action: Restore the stream by appending new events, or accept that the stream is deleted.
    Recoverable by appending to the stream to restore it.
    """
    STREAMS_ERROR_STREAM_TOMBSTONED: _StreamsError.ValueType  # 4
    """The stream has been tombstoned (permanently deleted).
    Tombstoned streams cannot be restored and will never accept new events.

    Common causes:
    - Stream was explicitly tombstoned via tombstone operation
    - Administrative deletion of sensitive data
    - Attempting to write to or read from a tombstoned stream

    Client action: Stream is permanently removed. Create a new stream with a different name if needed.
    Not recoverable - the stream cannot be restored.
    """
    STREAMS_ERROR_STREAM_REVISION_CONFLICT: _StreamsError.ValueType  # 5
    """The expected revision does not match the actual stream revision.
    This is an optimistic concurrency control failure.

    Common causes:
    - Another client modified the stream concurrently
    - Client has stale state about the stream revision
    - Race condition in distributed system

    Client action: Fetch the current stream revision and retry with the correct expected revision.
    Recoverable by reading the current state and retrying with proper optimistic concurrency control.
    """
    STREAMS_ERROR_APPEND_RECORD_SIZE_EXCEEDED: _StreamsError.ValueType  # 6
    """A single record being appended exceeds the maximum allowed size.

    Common causes:
    - Record payload is too large (exceeds server's max record size configuration)
    - Excessive metadata in properties
    - Large binary data without chunking

    Client action: Reduce record size, split large payloads across multiple records, or increase server limits.
    Recoverable by reducing record size or adjusting server configuration.
    """
    STREAMS_ERROR_APPEND_TRANSACTION_SIZE_EXCEEDED: _StreamsError.ValueType  # 7
    """The total size of all records in a single append session exceeds the maximum allowed transaction size.

    Common causes:
    - Too many records in a single append session
    - Combined payload size exceeds server's max transaction size
    - Attempting to write very large batches

    Client action: Split the append into multiple smaller transactions.
    Recoverable by reducing the number of records per append session.
    """
    STREAMS_ERROR_STREAM_ALREADY_IN_APPEND_SESSION: _StreamsError.ValueType  # 8
    """The same stream appears multiple times in a single append session.
    This is currently not supported to prevent complexity with expected revisions and ordering.

    Common causes:
    - Accidentally appending to the same stream twice in one session
    - Application logic error in batch operations

    Client action: Remove duplicate streams from the append session or split into multiple sessions.
    Recoverable by restructuring the append session to reference each stream only once.
    """
    STREAMS_ERROR_APPEND_SESSION_NO_REQUESTS: _StreamsError.ValueType  # 9
    """An append session was started but no append requests were sent before completing the stream.

    Common causes:
    - Client completed the stream without sending any AppendRequest messages
    - Application logic error

    Client action: Ensure at least one AppendRequest is sent before completing the stream.
    Recoverable by properly implementing the append session protocol.
    """

class StreamsError(_StreamsError, metaclass=_StreamsErrorEnumTypeWrapper):
    """Error codes specific to the Streams API.
    These errors represent failure modes when working with streams of records.
    """

STREAMS_ERROR_UNSPECIFIED: StreamsError.ValueType  # 0
"""Default value. This value is not used.
An error code MUST always be set to a non-zero value.
If an error code is not explicitly set, it MUST be treated as
an internal server error (INTERNAL).
"""
STREAMS_ERROR_STREAM_NOT_FOUND: StreamsError.ValueType  # 1
"""The requested stream does not exist in the database.

Common causes:
- Stream name typo or incorrect stream identifier
- Stream was never created (no events appended yet)
- Stream was deleted and not yet recreated

Client action: Verify the stream name is correct. Create the stream by appending to it.
Recoverable by creating the stream first (append with NO_STREAM expected revision).
"""
STREAMS_ERROR_STREAM_ALREADY_EXISTS: StreamsError.ValueType  # 2
"""The stream already exists when an operation expected it not to exist.

Common causes:
- Attempting to create a stream that already has events
- Using NO_STREAM expected revision on an existing stream
- Race condition with concurrent stream creation

Client action: Use the existing stream or use a different expected revision.
Recoverable by adjusting the expected revision or using the existing stream.
"""
STREAMS_ERROR_STREAM_DELETED: StreamsError.ValueType  # 3
"""The stream has been soft deleted.
Soft-deleted streams are hidden from stream lists but can be restored by appending to them.

Common causes:
- Stream was explicitly soft-deleted via delete operation
- Attempting to read from a soft-deleted stream

Client action: Restore the stream by appending new events, or accept that the stream is deleted.
Recoverable by appending to the stream to restore it.
"""
STREAMS_ERROR_STREAM_TOMBSTONED: StreamsError.ValueType  # 4
"""The stream has been tombstoned (permanently deleted).
Tombstoned streams cannot be restored and will never accept new events.

Common causes:
- Stream was explicitly tombstoned via tombstone operation
- Administrative deletion of sensitive data
- Attempting to write to or read from a tombstoned stream

Client action: Stream is permanently removed. Create a new stream with a different name if needed.
Not recoverable - the stream cannot be restored.
"""
STREAMS_ERROR_STREAM_REVISION_CONFLICT: StreamsError.ValueType  # 5
"""The expected revision does not match the actual stream revision.
This is an optimistic concurrency control failure.

Common causes:
- Another client modified the stream concurrently
- Client has stale state about the stream revision
- Race condition in distributed system

Client action: Fetch the current stream revision and retry with the correct expected revision.
Recoverable by reading the current state and retrying with proper optimistic concurrency control.
"""
STREAMS_ERROR_APPEND_RECORD_SIZE_EXCEEDED: StreamsError.ValueType  # 6
"""A single record being appended exceeds the maximum allowed size.

Common causes:
- Record payload is too large (exceeds server's max record size configuration)
- Excessive metadata in properties
- Large binary data without chunking

Client action: Reduce record size, split large payloads across multiple records, or increase server limits.
Recoverable by reducing record size or adjusting server configuration.
"""
STREAMS_ERROR_APPEND_TRANSACTION_SIZE_EXCEEDED: StreamsError.ValueType  # 7
"""The total size of all records in a single append session exceeds the maximum allowed transaction size.

Common causes:
- Too many records in a single append session
- Combined payload size exceeds server's max transaction size
- Attempting to write very large batches

Client action: Split the append into multiple smaller transactions.
Recoverable by reducing the number of records per append session.
"""
STREAMS_ERROR_STREAM_ALREADY_IN_APPEND_SESSION: StreamsError.ValueType  # 8
"""The same stream appears multiple times in a single append session.
This is currently not supported to prevent complexity with expected revisions and ordering.

Common causes:
- Accidentally appending to the same stream twice in one session
- Application logic error in batch operations

Client action: Remove duplicate streams from the append session or split into multiple sessions.
Recoverable by restructuring the append session to reference each stream only once.
"""
STREAMS_ERROR_APPEND_SESSION_NO_REQUESTS: StreamsError.ValueType  # 9
"""An append session was started but no append requests were sent before completing the stream.

Common causes:
- Client completed the stream without sending any AppendRequest messages
- Application logic error

Client action: Ensure at least one AppendRequest is sent before completing the stream.
Recoverable by properly implementing the append session protocol.
"""
global___StreamsError = StreamsError

@typing.final
class StreamNotFoundErrorDetails(google.protobuf.message.Message):
    """Details for STREAM_NOT_FOUND errors."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_FIELD_NUMBER: builtins.int
    stream: builtins.str
    """The name of the stream that was not found."""
    def __init__(
        self,
        *,
        stream: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["stream", b"stream"]) -> None: ...

global___StreamNotFoundErrorDetails = StreamNotFoundErrorDetails

@typing.final
class StreamAlreadyExistsErrorDetails(google.protobuf.message.Message):
    """Details for STREAM_ALREADY_EXISTS errors."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_FIELD_NUMBER: builtins.int
    stream: builtins.str
    """The name of the stream that already exists."""
    def __init__(
        self,
        *,
        stream: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["stream", b"stream"]) -> None: ...

global___StreamAlreadyExistsErrorDetails = StreamAlreadyExistsErrorDetails

@typing.final
class StreamDeletedErrorDetails(google.protobuf.message.Message):
    """Details for STREAM_DELETED errors."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_FIELD_NUMBER: builtins.int
    stream: builtins.str
    """The name of the stream that was deleted."""
    def __init__(
        self,
        *,
        stream: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["stream", b"stream"]) -> None: ...

global___StreamDeletedErrorDetails = StreamDeletedErrorDetails

@typing.final
class StreamTombstonedErrorDetails(google.protobuf.message.Message):
    """Details for STREAM_TOMBSTONED errors."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_FIELD_NUMBER: builtins.int
    stream: builtins.str
    """The name of the stream that was tombstoned."""
    def __init__(
        self,
        *,
        stream: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["stream", b"stream"]) -> None: ...

global___StreamTombstonedErrorDetails = StreamTombstonedErrorDetails

@typing.final
class StreamRevisionConflictErrorDetails(google.protobuf.message.Message):
    """Details for STREAM_REVISION_CONFLICT errors."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_FIELD_NUMBER: builtins.int
    EXPECTED_REVISION_FIELD_NUMBER: builtins.int
    ACTUAL_REVISION_FIELD_NUMBER: builtins.int
    stream: builtins.str
    """The name of the stream that had a revision conflict."""
    expected_revision: builtins.int
    """The expected revision that was provided in the append request."""
    actual_revision: builtins.int
    """The actual current revision of the stream."""
    def __init__(
        self,
        *,
        stream: builtins.str = ...,
        expected_revision: builtins.int = ...,
        actual_revision: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["actual_revision", b"actual_revision", "expected_revision", b"expected_revision", "stream", b"stream"]) -> None: ...

global___StreamRevisionConflictErrorDetails = StreamRevisionConflictErrorDetails

@typing.final
class AppendRecordSizeExceededErrorDetails(google.protobuf.message.Message):
    """Details for APPEND_RECORD_SIZE_EXCEEDED errors."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_FIELD_NUMBER: builtins.int
    RECORD_ID_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    MAX_SIZE_FIELD_NUMBER: builtins.int
    stream: builtins.str
    """The name of the stream where the append was attempted."""
    record_id: builtins.str
    """The identifier of the record that exceeded the size limit."""
    size: builtins.int
    """The actual size of the record in bytes."""
    max_size: builtins.int
    """The maximum allowed size of a single record in bytes."""
    def __init__(
        self,
        *,
        stream: builtins.str = ...,
        record_id: builtins.str = ...,
        size: builtins.int = ...,
        max_size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["max_size", b"max_size", "record_id", b"record_id", "size", b"size", "stream", b"stream"]) -> None: ...

global___AppendRecordSizeExceededErrorDetails = AppendRecordSizeExceededErrorDetails

@typing.final
class AppendTransactionSizeExceededErrorDetails(google.protobuf.message.Message):
    """Details for APPEND_TRANSACTION_SIZE_EXCEEDED errors."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SIZE_FIELD_NUMBER: builtins.int
    MAX_SIZE_FIELD_NUMBER: builtins.int
    size: builtins.int
    """The actual size of the transaction in bytes."""
    max_size: builtins.int
    """The maximum allowed size of an append transaction in bytes."""
    def __init__(
        self,
        *,
        size: builtins.int = ...,
        max_size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["max_size", b"max_size", "size", b"size"]) -> None: ...

global___AppendTransactionSizeExceededErrorDetails = AppendTransactionSizeExceededErrorDetails

@typing.final
class StreamAlreadyInAppendSessionErrorDetails(google.protobuf.message.Message):
    """Details for STREAM_ALREADY_IN_APPEND_SESSION errors."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_FIELD_NUMBER: builtins.int
    stream: builtins.str
    """The name of the stream that appears multiple times."""
    def __init__(
        self,
        *,
        stream: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["stream", b"stream"]) -> None: ...

global___StreamAlreadyInAppendSessionErrorDetails = StreamAlreadyInAppendSessionErrorDetails
