# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kurrentdbclient.protos.v2.streams import streams_pb2 as kurrentdbclient_dot_protos_dot_v2_dot_streams_dot_streams__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kurrentdbclient/protos/v2/streams/streams_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AppendSession = channel.stream_unary(
                '/kurrentdb.protocol.v2.streams.StreamsService/AppendSession',
                request_serializer=kurrentdbclient_dot_protos_dot_v2_dot_streams_dot_streams__pb2.AppendRequest.SerializeToString,
                response_deserializer=kurrentdbclient_dot_protos_dot_v2_dot_streams_dot_streams__pb2.AppendSessionResponse.FromString,
                _registered_method=True)


class StreamsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AppendSession(self, request_iterator, context):
        """Appends records to multiple streams atomically within a single transaction.

        This is a client-streaming RPC where the client sends multiple AppendRequest messages
        (one per stream) and receives a single AppendSessionResponse upon commit.

        Guarantees:
        - Atomicity: All writes succeed or all fail together
        - Optimistic Concurrency: Expected revisions are validated for all streams before commit
        - Ordering: Records within each stream maintain send order

        Current Limitations:
        - Each stream can only appear once per session (no multiple appends to same stream)

        Example flow:
        1. Client opens stream
        2. Client sends AppendRequest for stream "orders" with 3 records
        3. Client sends AppendRequest for stream "inventory" with 2 records
        4. Client completes the stream
        5. Server validates, commits, returns AppendSessionResponse with positions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AppendSession': grpc.stream_unary_rpc_method_handler(
                    servicer.AppendSession,
                    request_deserializer=kurrentdbclient_dot_protos_dot_v2_dot_streams_dot_streams__pb2.AppendRequest.FromString,
                    response_serializer=kurrentdbclient_dot_protos_dot_v2_dot_streams_dot_streams__pb2.AppendSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kurrentdb.protocol.v2.streams.StreamsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kurrentdb.protocol.v2.streams.StreamsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AppendSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/kurrentdb.protocol.v2.streams.StreamsService/AppendSession',
            kurrentdbclient_dot_protos_dot_v2_dot_streams_dot_streams__pb2.AppendRequest.SerializeToString,
            kurrentdbclient_dot_protos_dot_v2_dot_streams_dot_streams__pb2.AppendSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
