"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
******************************************************************************************
This protocol is UNSTABLE in the sense of being subject to change.
******************************************************************************************
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _SchemaFormat:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SchemaFormatEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SchemaFormat.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SCHEMA_FORMAT_UNSPECIFIED: _SchemaFormat.ValueType  # 0
    """Default value, should not be used."""
    SCHEMA_FORMAT_JSON: _SchemaFormat.ValueType  # 1
    SCHEMA_FORMAT_PROTOBUF: _SchemaFormat.ValueType  # 2
    SCHEMA_FORMAT_AVRO: _SchemaFormat.ValueType  # 3
    SCHEMA_FORMAT_BYTES: _SchemaFormat.ValueType  # 4

class SchemaFormat(_SchemaFormat, metaclass=_SchemaFormatEnumTypeWrapper):
    """Represents the data format of the schema."""

SCHEMA_FORMAT_UNSPECIFIED: SchemaFormat.ValueType  # 0
"""Default value, should not be used."""
SCHEMA_FORMAT_JSON: SchemaFormat.ValueType  # 1
SCHEMA_FORMAT_PROTOBUF: SchemaFormat.ValueType  # 2
SCHEMA_FORMAT_AVRO: SchemaFormat.ValueType  # 3
SCHEMA_FORMAT_BYTES: SchemaFormat.ValueType  # 4
Global___SchemaFormat: _TypeAlias = SchemaFormat  # noqa: Y015

class _ExpectedRevisionConstants:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ExpectedRevisionConstantsEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ExpectedRevisionConstants.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    EXPECTED_REVISION_CONSTANTS_SINGLE_EVENT: _ExpectedRevisionConstants.ValueType  # 0
    """The stream must have exactly one event at revision 0.
    Used for scenarios requiring strict single-event semantics.
    """
    EXPECTED_REVISION_CONSTANTS_NO_STREAM: _ExpectedRevisionConstants.ValueType  # -1
    """The stream must not exist yet (first write to the stream).
    Fails if the stream already has events.
    """
    EXPECTED_REVISION_CONSTANTS_ANY: _ExpectedRevisionConstants.ValueType  # -2
    """Accept any current state of the stream (no optimistic concurrency check).
    The write will succeed regardless of the stream's current revision.
    """
    EXPECTED_REVISION_CONSTANTS_EXISTS: _ExpectedRevisionConstants.ValueType  # -4
    """The stream must exist (have at least one record).
    Fails if the stream doesn't exist yet.
    """

class ExpectedRevisionConstants(_ExpectedRevisionConstants, metaclass=_ExpectedRevisionConstantsEnumTypeWrapper):
    """Constants for expected revision validation in optimistic concurrency control.
    These can be used in the expected_revision field, or you can specify an actual revision number.
    """

EXPECTED_REVISION_CONSTANTS_SINGLE_EVENT: ExpectedRevisionConstants.ValueType  # 0
"""The stream must have exactly one event at revision 0.
Used for scenarios requiring strict single-event semantics.
"""
EXPECTED_REVISION_CONSTANTS_NO_STREAM: ExpectedRevisionConstants.ValueType  # -1
"""The stream must not exist yet (first write to the stream).
Fails if the stream already has events.
"""
EXPECTED_REVISION_CONSTANTS_ANY: ExpectedRevisionConstants.ValueType  # -2
"""Accept any current state of the stream (no optimistic concurrency check).
The write will succeed regardless of the stream's current revision.
"""
EXPECTED_REVISION_CONSTANTS_EXISTS: ExpectedRevisionConstants.ValueType  # -4
"""The stream must exist (have at least one record).
Fails if the stream doesn't exist yet.
"""
Global___ExpectedRevisionConstants: _TypeAlias = ExpectedRevisionConstants  # noqa: Y015

@_typing.final
class AppendRequest(_message.Message):
    """Represents the input for appending records to a specific stream."""

    DESCRIPTOR: _descriptor.Descriptor

    STREAM_FIELD_NUMBER: _builtins.int
    RECORDS_FIELD_NUMBER: _builtins.int
    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    stream: _builtins.str
    """The stream to append records to."""
    expected_revision: _builtins.int
    """The expected revision for optimistic concurrency control.
    Can be either:
    - A specific revision number (0, 1, 2, ...) - the stream must be at exactly this revision
    - An ExpectedRevisionConstants value (-4, -2, -1) for special semantics

    If omitted, defaults to EXPECTED_REVISION_CONSTANTS_ANY (-2).
    """
    @_builtins.property
    def records(self) -> _containers.RepeatedCompositeFieldContainer[Global___AppendRecord]:
        """The records to append to the stream."""

    def __init__(
        self,
        *,
        stream: _builtins.str = ...,
        records: _abc.Iterable[Global___AppendRecord] | None = ...,
        expected_revision: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_expected_revision", b"_expected_revision", "expected_revision", b"expected_revision"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_expected_revision", b"_expected_revision", "expected_revision", b"expected_revision", "records", b"records", "stream", b"stream"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__expected_revision: _TypeAlias = _typing.Literal["expected_revision"]  # noqa: Y015
    _WhichOneofArgType__expected_revision: _TypeAlias = _typing.Literal["_expected_revision", b"_expected_revision"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__expected_revision) -> _WhichOneofReturnType__expected_revision | None: ...

Global___AppendRequest: _TypeAlias = AppendRequest  # noqa: Y015

@_typing.final
class AppendResponse(_message.Message):
    """Represents the outcome of an append operation."""

    DESCRIPTOR: _descriptor.Descriptor

    STREAM_FIELD_NUMBER: _builtins.int
    STREAM_REVISION_FIELD_NUMBER: _builtins.int
    POSITION_FIELD_NUMBER: _builtins.int
    stream: _builtins.str
    """The stream to which records were appended."""
    stream_revision: _builtins.int
    """The actual/current revision of the stream after the append.
    This is the revision number of the last record written to this stream.
    """
    position: _builtins.int
    """The position of the last appended record in the global log."""
    def __init__(
        self,
        *,
        stream: _builtins.str = ...,
        stream_revision: _builtins.int = ...,
        position: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_position", b"_position", "position", b"position"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_position", b"_position", "position", b"position", "stream", b"stream", "stream_revision", b"stream_revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__position: _TypeAlias = _typing.Literal["position"]  # noqa: Y015
    _WhichOneofArgType__position: _TypeAlias = _typing.Literal["_position", b"_position"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__position) -> _WhichOneofReturnType__position | None: ...

Global___AppendResponse: _TypeAlias = AppendResponse  # noqa: Y015

@_typing.final
class AppendSessionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OUTPUT_FIELD_NUMBER: _builtins.int
    POSITION_FIELD_NUMBER: _builtins.int
    position: _builtins.int
    """The global commit position of the last appended record in the session."""
    @_builtins.property
    def output(self) -> _containers.RepeatedCompositeFieldContainer[Global___AppendResponse]:
        """The results of each append request in the session."""

    def __init__(
        self,
        *,
        output: _abc.Iterable[Global___AppendResponse] | None = ...,
        position: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["output", b"output", "position", b"position"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AppendSessionResponse: _TypeAlias = AppendSessionResponse  # noqa: Y015

@_typing.final
class SchemaInfo(_message.Message):
    """Schema information for record validation and interpretation."""

    DESCRIPTOR: _descriptor.Descriptor

    FORMAT_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    ID_FIELD_NUMBER: _builtins.int
    format: Global___SchemaFormat.ValueType
    """The format of the data payload.
    Determines how the bytes in AppendRecord.data should be interpreted.
    """
    name: _builtins.str
    """The schema name (replaces the legacy "event type" concept).
    Identifies what kind of data this record contains.

    Common naming formats:
      - Kebab-case: "order-placed", "customer-registered"
      - URN format: "urn:kurrentdb:events:order-placed:v1"
      - Dotted namespace: "Teams.Player.V1", "Orders.OrderPlaced.V2"
      - Reverse domain: "com.acme.orders.placed"
    """
    id: _builtins.str
    """The identifier of the specific version of the schema that the record payload
    conforms to. This should match a registered schema version in the system.
    Not necessary when not enforcing schema validation.
    """
    def __init__(
        self,
        *,
        format: Global___SchemaFormat.ValueType = ...,
        name: _builtins.str = ...,
        id: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_id", b"_id", "id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_id", b"_id", "format", b"format", "id", b"id", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__id: _TypeAlias = _typing.Literal["id"]  # noqa: Y015
    _WhichOneofArgType__id: _TypeAlias = _typing.Literal["_id", b"_id"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__id) -> _WhichOneofReturnType__id | None: ...

Global___SchemaInfo: _TypeAlias = SchemaInfo  # noqa: Y015

@_typing.final
class AppendRecord(_message.Message):
    """Record to be appended to a stream."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class PropertiesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> _struct_pb2.Value: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _struct_pb2.Value | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    RECORD_ID_FIELD_NUMBER: _builtins.int
    PROPERTIES_FIELD_NUMBER: _builtins.int
    SCHEMA_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    STREAM_FIELD_NUMBER: _builtins.int
    record_id: _builtins.str
    """Unique identifier for this record (must be a valid UUID/GUID).
    If not provided, the server will generate a new one.
    """
    data: _builtins.bytes
    """The record payload as raw bytes.
    The format specified in SchemaInfo determines how to interpret these bytes.
    """
    stream: _builtins.str
    """Target stream for this record.
    Required for AppendRecords (each record specifies its own stream).
    Ignored for AppendSession (the stream is specified in AppendRequest).
    """
    @_builtins.property
    def properties(self) -> _containers.MessageMap[_builtins.str, _struct_pb2.Value]:
        """A collection of properties providing additional information about the
        record. Can contain user-defined or system propreties.
        System keys will be prefixed with "$" (e.g., "$timestamp").
        User-defined keys MUST NOT start with "$".

        Common examples:
          User metadata:
            - "user-id": "12345"
            - "tenant": "acme-corp"
            - "source": "mobile-app"

          System metadata (with $ prefix):
            - "$trace-id": "4bf92f3577b34da6a3ce929d0e0e4736"  // OpenTelemetry trace ID
            - "$span-id": "00f067aa0ba902b7"                   // OpenTelemetry span ID
            - "$timestamp": "2025-01-15T10:30:00.000Z"         // ISO 8601 timestamp
        """

    @_builtins.property
    def schema(self) -> Global___SchemaInfo:
        """Schema information for this record."""

    def __init__(
        self,
        *,
        record_id: _builtins.str | None = ...,
        properties: _abc.Mapping[_builtins.str, _struct_pb2.Value] | None = ...,
        schema: Global___SchemaInfo | None = ...,
        data: _builtins.bytes = ...,
        stream: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_record_id", b"_record_id", "record_id", b"record_id", "schema", b"schema"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_record_id", b"_record_id", "data", b"data", "properties", b"properties", "record_id", b"record_id", "schema", b"schema", "stream", b"stream"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__record_id: _TypeAlias = _typing.Literal["record_id"]  # noqa: Y015
    _WhichOneofArgType__record_id: _TypeAlias = _typing.Literal["_record_id", b"_record_id"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__record_id) -> _WhichOneofReturnType__record_id | None: ...

Global___AppendRecord: _TypeAlias = AppendRecord  # noqa: Y015

@_typing.final
class AppendRecordsRequest(_message.Message):
    """*
    Request to append records to one or more streams atomically.

    All records are committed in a single transaction. Each record specifies its
    target stream via AppendRecord.stream. Consistency checks are evaluated before
    any records are written.
    """

    DESCRIPTOR: _descriptor.Descriptor

    RECORDS_FIELD_NUMBER: _builtins.int
    CHECKS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def records(self) -> _containers.RepeatedCompositeFieldContainer[Global___AppendRecord]:
        """The records to append. Records targeting the same stream maintain their
        order from this list.
        """

    @_builtins.property
    def checks(self) -> _containers.RepeatedCompositeFieldContainer[Global___ConsistencyCheck]:
        """Optional consistency checks evaluated before commit. If any check fails,
        the entire transaction is aborted.
        """

    def __init__(
        self,
        *,
        records: _abc.Iterable[Global___AppendRecord] | None = ...,
        checks: _abc.Iterable[Global___ConsistencyCheck] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["checks", b"checks", "records", b"records"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AppendRecordsRequest: _TypeAlias = AppendRecordsRequest  # noqa: Y015

@_typing.final
class AppendRecordsResponse(_message.Message):
    """*
    Response from a successful AppendRecords operation.

    Contains the resulting revision for each stream that was written to and the
    global commit position of the transaction.
    """

    DESCRIPTOR: _descriptor.Descriptor

    REVISIONS_FIELD_NUMBER: _builtins.int
    POSITION_FIELD_NUMBER: _builtins.int
    position: _builtins.int
    """The global commit position of the last record written in this transaction.
    Can be used for read-your-writes consistency or progress tracking.
    """
    @_builtins.property
    def revisions(self) -> _containers.RepeatedCompositeFieldContainer[Global___StreamRevision]:
        """The resulting revision for each stream that received records. One entry per
        distinct stream written to, in no guaranteed order.
        """

    def __init__(
        self,
        *,
        revisions: _abc.Iterable[Global___StreamRevision] | None = ...,
        position: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["position", b"position", "revisions", b"revisions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AppendRecordsResponse: _TypeAlias = AppendRecordsResponse  # noqa: Y015

@_typing.final
class ConsistencyCheck(_message.Message):
    """*
    A pre-commit condition that must hold true for the transaction to succeed.

    Consistency checks are evaluated atomically before any records are written. If
    any check is violated, the entire transaction is aborted. Two types of checks
    are supported: stream state checks (validates a stream's revision or lifecycle
    state) and query predicates (evaluates a server-side expression).
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class StreamStateCheck(_message.Message):
        """*
        Asserts a stream is at a specific revision or lifecycle state before commit.

        The expected_state field accepts a specific revision number (>= 0) or a
        special state constant (e.g., -1 for NO_STREAM, -10 for DELETED). Evaluated
        using writability semantics: a soft-deleted stream is writable (appending
        restores it), but a tombstoned stream is never writable.
        """

        DESCRIPTOR: _descriptor.Descriptor

        STREAM_FIELD_NUMBER: _builtins.int
        EXPECTED_STATE_FIELD_NUMBER: _builtins.int
        stream: _builtins.str
        """The stream name."""
        expected_state: _builtins.int
        """The expected state of the stream (revision number or state constant)."""
        def __init__(
            self,
            *,
            stream: _builtins.str = ...,
            expected_state: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["expected_state", b"expected_state", "stream", b"stream"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    STREAM_STATE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stream_state(self) -> Global___ConsistencyCheck.StreamStateCheck:
        """Check that a stream is at a specific revision or lifecycle state."""

    def __init__(
        self,
        *,
        stream_state: Global___ConsistencyCheck.StreamStateCheck | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stream_state", b"stream_state", "type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stream_state", b"stream_state", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_type: _TypeAlias = _typing.Literal["stream_state"]  # noqa: Y015
    _WhichOneofArgType_type: _TypeAlias = _typing.Literal["type", b"type"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_type) -> _WhichOneofReturnType_type | None: ...

Global___ConsistencyCheck: _TypeAlias = ConsistencyCheck  # noqa: Y015

@_typing.final
class StreamRevision(_message.Message):
    """*
    A specific revision of a stream.

    Used to represent stream positions for checkpoints, consistency checks,
    and head position tracking.
    """

    DESCRIPTOR: _descriptor.Descriptor

    STREAM_FIELD_NUMBER: _builtins.int
    REVISION_FIELD_NUMBER: _builtins.int
    stream: _builtins.str
    """Stream name."""
    revision: _builtins.int
    """Revision within the stream."""
    def __init__(
        self,
        *,
        stream: _builtins.str = ...,
        revision: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revision", b"revision", "stream", b"stream"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StreamRevision: _TypeAlias = StreamRevision  # noqa: Y015
