"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import empty_pb2 as _empty_pb2
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from kurrentdbclient.protos.v1 import shared_pb2 as _shared_pb2
from kurrentdbclient.protos.v1 import status_pb2 as _status_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ReadReq(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Options(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        class _ReadDirection:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _ReadDirectionEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ReadReq.Options._ReadDirection.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            Forwards: ReadReq.Options._ReadDirection.ValueType  # 0
            Backwards: ReadReq.Options._ReadDirection.ValueType  # 1

        class ReadDirection(_ReadDirection, metaclass=_ReadDirectionEnumTypeWrapper): ...
        Forwards: ReadReq.Options.ReadDirection.ValueType  # 0
        Backwards: ReadReq.Options.ReadDirection.ValueType  # 1

        @_typing.final
        class StreamOptions(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            STREAM_IDENTIFIER_FIELD_NUMBER: _builtins.int
            REVISION_FIELD_NUMBER: _builtins.int
            START_FIELD_NUMBER: _builtins.int
            END_FIELD_NUMBER: _builtins.int
            revision: _builtins.int
            @_builtins.property
            def stream_identifier(self) -> _shared_pb2.StreamIdentifier: ...
            @_builtins.property
            def start(self) -> _shared_pb2.Empty: ...
            @_builtins.property
            def end(self) -> _shared_pb2.Empty: ...
            def __init__(
                self,
                *,
                stream_identifier: _shared_pb2.StreamIdentifier | None = ...,
                revision: _builtins.int = ...,
                start: _shared_pb2.Empty | None = ...,
                end: _shared_pb2.Empty | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["end", b"end", "revision", b"revision", "revision_option", b"revision_option", "start", b"start", "stream_identifier", b"stream_identifier"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["end", b"end", "revision", b"revision", "revision_option", b"revision_option", "start", b"start", "stream_identifier", b"stream_identifier"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            _WhichOneofReturnType_revision_option: _TypeAlias = _typing.Literal["revision", "start", "end"]  # noqa: Y015
            _WhichOneofArgType_revision_option: _TypeAlias = _typing.Literal["revision_option", b"revision_option"]  # noqa: Y015
            def WhichOneof(self, oneof_group: _WhichOneofArgType_revision_option) -> _WhichOneofReturnType_revision_option | None: ...

        @_typing.final
        class AllOptions(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            POSITION_FIELD_NUMBER: _builtins.int
            START_FIELD_NUMBER: _builtins.int
            END_FIELD_NUMBER: _builtins.int
            @_builtins.property
            def position(self) -> Global___ReadReq.Options.Position: ...
            @_builtins.property
            def start(self) -> _shared_pb2.Empty: ...
            @_builtins.property
            def end(self) -> _shared_pb2.Empty: ...
            def __init__(
                self,
                *,
                position: Global___ReadReq.Options.Position | None = ...,
                start: _shared_pb2.Empty | None = ...,
                end: _shared_pb2.Empty | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["all_option", b"all_option", "end", b"end", "position", b"position", "start", b"start"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["all_option", b"all_option", "end", b"end", "position", b"position", "start", b"start"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            _WhichOneofReturnType_all_option: _TypeAlias = _typing.Literal["position", "start", "end"]  # noqa: Y015
            _WhichOneofArgType_all_option: _TypeAlias = _typing.Literal["all_option", b"all_option"]  # noqa: Y015
            def WhichOneof(self, oneof_group: _WhichOneofArgType_all_option) -> _WhichOneofReturnType_all_option | None: ...

        @_typing.final
        class SubscriptionOptions(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            def __init__(
                self,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        @_typing.final
        class Position(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            COMMIT_POSITION_FIELD_NUMBER: _builtins.int
            PREPARE_POSITION_FIELD_NUMBER: _builtins.int
            commit_position: _builtins.int
            prepare_position: _builtins.int
            def __init__(
                self,
                *,
                commit_position: _builtins.int = ...,
                prepare_position: _builtins.int = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["commit_position", b"commit_position", "prepare_position", b"prepare_position"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        @_typing.final
        class FilterOptions(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            @_typing.final
            class Expression(_message.Message):
                DESCRIPTOR: _descriptor.Descriptor

                REGEX_FIELD_NUMBER: _builtins.int
                PREFIX_FIELD_NUMBER: _builtins.int
                regex: _builtins.str
                @_builtins.property
                def prefix(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
                def __init__(
                    self,
                    *,
                    regex: _builtins.str = ...,
                    prefix: _abc.Iterable[_builtins.str] | None = ...,
                ) -> None: ...
                _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
                def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
                _ClearFieldArgType: _TypeAlias = _typing.Literal["prefix", b"prefix", "regex", b"regex"]  # noqa: Y015
                def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
                def WhichOneof(self, oneof_group: _Never) -> None: ...

            STREAM_IDENTIFIER_FIELD_NUMBER: _builtins.int
            EVENT_TYPE_FIELD_NUMBER: _builtins.int
            MAX_FIELD_NUMBER: _builtins.int
            COUNT_FIELD_NUMBER: _builtins.int
            CHECKPOINTINTERVALMULTIPLIER_FIELD_NUMBER: _builtins.int
            max: _builtins.int
            checkpointIntervalMultiplier: _builtins.int
            @_builtins.property
            def stream_identifier(self) -> Global___ReadReq.Options.FilterOptions.Expression: ...
            @_builtins.property
            def event_type(self) -> Global___ReadReq.Options.FilterOptions.Expression: ...
            @_builtins.property
            def count(self) -> _shared_pb2.Empty: ...
            def __init__(
                self,
                *,
                stream_identifier: Global___ReadReq.Options.FilterOptions.Expression | None = ...,
                event_type: Global___ReadReq.Options.FilterOptions.Expression | None = ...,
                max: _builtins.int = ...,
                count: _shared_pb2.Empty | None = ...,
                checkpointIntervalMultiplier: _builtins.int = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["count", b"count", "event_type", b"event_type", "filter", b"filter", "max", b"max", "stream_identifier", b"stream_identifier", "window", b"window"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["checkpointIntervalMultiplier", b"checkpointIntervalMultiplier", "count", b"count", "event_type", b"event_type", "filter", b"filter", "max", b"max", "stream_identifier", b"stream_identifier", "window", b"window"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            _WhichOneofReturnType_filter: _TypeAlias = _typing.Literal["stream_identifier", "event_type"]  # noqa: Y015
            _WhichOneofArgType_filter: _TypeAlias = _typing.Literal["filter", b"filter"]  # noqa: Y015
            _WhichOneofReturnType_window: _TypeAlias = _typing.Literal["max", "count"]  # noqa: Y015
            _WhichOneofArgType_window: _TypeAlias = _typing.Literal["window", b"window"]  # noqa: Y015
            @_typing.overload
            def WhichOneof(self, oneof_group: _WhichOneofArgType_filter) -> _WhichOneofReturnType_filter | None: ...
            @_typing.overload
            def WhichOneof(self, oneof_group: _WhichOneofArgType_window) -> _WhichOneofReturnType_window | None: ...

        @_typing.final
        class UUIDOption(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            STRUCTURED_FIELD_NUMBER: _builtins.int
            STRING_FIELD_NUMBER: _builtins.int
            @_builtins.property
            def structured(self) -> _shared_pb2.Empty: ...
            @_builtins.property
            def string(self) -> _shared_pb2.Empty: ...
            def __init__(
                self,
                *,
                structured: _shared_pb2.Empty | None = ...,
                string: _shared_pb2.Empty | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "string", b"string", "structured", b"structured"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "string", b"string", "structured", b"structured"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            _WhichOneofReturnType_content: _TypeAlias = _typing.Literal["structured", "string"]  # noqa: Y015
            _WhichOneofArgType_content: _TypeAlias = _typing.Literal["content", b"content"]  # noqa: Y015
            def WhichOneof(self, oneof_group: _WhichOneofArgType_content) -> _WhichOneofReturnType_content | None: ...

        @_typing.final
        class ControlOption(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            COMPATIBILITY_FIELD_NUMBER: _builtins.int
            compatibility: _builtins.int
            def __init__(
                self,
                *,
                compatibility: _builtins.int = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["compatibility", b"compatibility"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        STREAM_FIELD_NUMBER: _builtins.int
        ALL_FIELD_NUMBER: _builtins.int
        READ_DIRECTION_FIELD_NUMBER: _builtins.int
        RESOLVE_LINKS_FIELD_NUMBER: _builtins.int
        COUNT_FIELD_NUMBER: _builtins.int
        SUBSCRIPTION_FIELD_NUMBER: _builtins.int
        FILTER_FIELD_NUMBER: _builtins.int
        NO_FILTER_FIELD_NUMBER: _builtins.int
        UUID_OPTION_FIELD_NUMBER: _builtins.int
        CONTROL_OPTION_FIELD_NUMBER: _builtins.int
        read_direction: Global___ReadReq.Options.ReadDirection.ValueType
        resolve_links: _builtins.bool
        count: _builtins.int
        @_builtins.property
        def stream(self) -> Global___ReadReq.Options.StreamOptions: ...
        @_builtins.property
        def all(self) -> Global___ReadReq.Options.AllOptions: ...
        @_builtins.property
        def subscription(self) -> Global___ReadReq.Options.SubscriptionOptions: ...
        @_builtins.property
        def filter(self) -> Global___ReadReq.Options.FilterOptions: ...
        @_builtins.property
        def no_filter(self) -> _shared_pb2.Empty: ...
        @_builtins.property
        def uuid_option(self) -> Global___ReadReq.Options.UUIDOption: ...
        @_builtins.property
        def control_option(self) -> Global___ReadReq.Options.ControlOption: ...
        def __init__(
            self,
            *,
            stream: Global___ReadReq.Options.StreamOptions | None = ...,
            all: Global___ReadReq.Options.AllOptions | None = ...,
            read_direction: Global___ReadReq.Options.ReadDirection.ValueType = ...,
            resolve_links: _builtins.bool = ...,
            count: _builtins.int = ...,
            subscription: Global___ReadReq.Options.SubscriptionOptions | None = ...,
            filter: Global___ReadReq.Options.FilterOptions | None = ...,
            no_filter: _shared_pb2.Empty | None = ...,
            uuid_option: Global___ReadReq.Options.UUIDOption | None = ...,
            control_option: Global___ReadReq.Options.ControlOption | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["all", b"all", "control_option", b"control_option", "count", b"count", "count_option", b"count_option", "filter", b"filter", "filter_option", b"filter_option", "no_filter", b"no_filter", "stream", b"stream", "stream_option", b"stream_option", "subscription", b"subscription", "uuid_option", b"uuid_option"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["all", b"all", "control_option", b"control_option", "count", b"count", "count_option", b"count_option", "filter", b"filter", "filter_option", b"filter_option", "no_filter", b"no_filter", "read_direction", b"read_direction", "resolve_links", b"resolve_links", "stream", b"stream", "stream_option", b"stream_option", "subscription", b"subscription", "uuid_option", b"uuid_option"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_count_option: _TypeAlias = _typing.Literal["count", "subscription"]  # noqa: Y015
        _WhichOneofArgType_count_option: _TypeAlias = _typing.Literal["count_option", b"count_option"]  # noqa: Y015
        _WhichOneofReturnType_filter_option: _TypeAlias = _typing.Literal["filter", "no_filter"]  # noqa: Y015
        _WhichOneofArgType_filter_option: _TypeAlias = _typing.Literal["filter_option", b"filter_option"]  # noqa: Y015
        _WhichOneofReturnType_stream_option: _TypeAlias = _typing.Literal["stream", "all"]  # noqa: Y015
        _WhichOneofArgType_stream_option: _TypeAlias = _typing.Literal["stream_option", b"stream_option"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType_count_option) -> _WhichOneofReturnType_count_option | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType_filter_option) -> _WhichOneofReturnType_filter_option | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType_stream_option) -> _WhichOneofReturnType_stream_option | None: ...

    OPTIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def options(self) -> Global___ReadReq.Options: ...
    def __init__(
        self,
        *,
        options: Global___ReadReq.Options | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["options", b"options"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["options", b"options"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReadReq: _TypeAlias = ReadReq  # noqa: Y015

@_typing.final
class ReadResp(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ReadEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class RecordedEvent(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            @_typing.final
            class MetadataEntry(_message.Message):
                DESCRIPTOR: _descriptor.Descriptor

                KEY_FIELD_NUMBER: _builtins.int
                VALUE_FIELD_NUMBER: _builtins.int
                key: _builtins.str
                value: _builtins.str
                def __init__(
                    self,
                    *,
                    key: _builtins.str = ...,
                    value: _builtins.str = ...,
                ) -> None: ...
                _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
                def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
                _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
                def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
                def WhichOneof(self, oneof_group: _Never) -> None: ...

            ID_FIELD_NUMBER: _builtins.int
            STREAM_IDENTIFIER_FIELD_NUMBER: _builtins.int
            STREAM_REVISION_FIELD_NUMBER: _builtins.int
            PREPARE_POSITION_FIELD_NUMBER: _builtins.int
            COMMIT_POSITION_FIELD_NUMBER: _builtins.int
            METADATA_FIELD_NUMBER: _builtins.int
            CUSTOM_METADATA_FIELD_NUMBER: _builtins.int
            DATA_FIELD_NUMBER: _builtins.int
            stream_revision: _builtins.int
            prepare_position: _builtins.int
            commit_position: _builtins.int
            custom_metadata: _builtins.bytes
            data: _builtins.bytes
            @_builtins.property
            def id(self) -> _shared_pb2.UUID: ...
            @_builtins.property
            def stream_identifier(self) -> _shared_pb2.StreamIdentifier: ...
            @_builtins.property
            def metadata(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
            def __init__(
                self,
                *,
                id: _shared_pb2.UUID | None = ...,
                stream_identifier: _shared_pb2.StreamIdentifier | None = ...,
                stream_revision: _builtins.int = ...,
                prepare_position: _builtins.int = ...,
                commit_position: _builtins.int = ...,
                metadata: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
                custom_metadata: _builtins.bytes = ...,
                data: _builtins.bytes = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "stream_identifier", b"stream_identifier"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["commit_position", b"commit_position", "custom_metadata", b"custom_metadata", "data", b"data", "id", b"id", "metadata", b"metadata", "prepare_position", b"prepare_position", "stream_identifier", b"stream_identifier", "stream_revision", b"stream_revision"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        EVENT_FIELD_NUMBER: _builtins.int
        LINK_FIELD_NUMBER: _builtins.int
        COMMIT_POSITION_FIELD_NUMBER: _builtins.int
        NO_POSITION_FIELD_NUMBER: _builtins.int
        commit_position: _builtins.int
        @_builtins.property
        def event(self) -> Global___ReadResp.ReadEvent.RecordedEvent: ...
        @_builtins.property
        def link(self) -> Global___ReadResp.ReadEvent.RecordedEvent: ...
        @_builtins.property
        def no_position(self) -> _shared_pb2.Empty: ...
        def __init__(
            self,
            *,
            event: Global___ReadResp.ReadEvent.RecordedEvent | None = ...,
            link: Global___ReadResp.ReadEvent.RecordedEvent | None = ...,
            commit_position: _builtins.int = ...,
            no_position: _shared_pb2.Empty | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["commit_position", b"commit_position", "event", b"event", "link", b"link", "no_position", b"no_position", "position", b"position"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["commit_position", b"commit_position", "event", b"event", "link", b"link", "no_position", b"no_position", "position", b"position"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_position: _TypeAlias = _typing.Literal["commit_position", "no_position"]  # noqa: Y015
        _WhichOneofArgType_position: _TypeAlias = _typing.Literal["position", b"position"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_position) -> _WhichOneofReturnType_position | None: ...

    @_typing.final
    class SubscriptionConfirmation(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SUBSCRIPTION_ID_FIELD_NUMBER: _builtins.int
        subscription_id: _builtins.str
        def __init__(
            self,
            *,
            subscription_id: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["subscription_id", b"subscription_id"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class Checkpoint(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        COMMIT_POSITION_FIELD_NUMBER: _builtins.int
        PREPARE_POSITION_FIELD_NUMBER: _builtins.int
        TIMESTAMP_FIELD_NUMBER: _builtins.int
        commit_position: _builtins.int
        prepare_position: _builtins.int
        @_builtins.property
        def timestamp(self) -> _timestamp_pb2.Timestamp:
            """Current time in the server when the checkpoint was reached"""

        def __init__(
            self,
            *,
            commit_position: _builtins.int = ...,
            prepare_position: _builtins.int = ...,
            timestamp: _timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp", b"timestamp"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["commit_position", b"commit_position", "prepare_position", b"prepare_position", "timestamp", b"timestamp"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CaughtUp(_message.Message):
        """The $all or stream subscription has caught up and become live."""

        DESCRIPTOR: _descriptor.Descriptor

        TIMESTAMP_FIELD_NUMBER: _builtins.int
        STREAM_REVISION_FIELD_NUMBER: _builtins.int
        POSITION_FIELD_NUMBER: _builtins.int
        stream_revision: _builtins.int
        """Checkpoint for resuming a stream subscription.
        For stream subscriptions it is populated unless the stream is empty.
        For $all subscriptions it is not populated.
        """
        @_builtins.property
        def timestamp(self) -> _timestamp_pb2.Timestamp:
            """Current time in the server when the subscription caught up"""

        @_builtins.property
        def position(self) -> Global___ReadResp.Position:
            """Checkpoint for resuming a $all subscription.
            For stream subscriptions it is not populated.
            For $all subscriptions it is populated unless the database is empty.
            """

        def __init__(
            self,
            *,
            timestamp: _timestamp_pb2.Timestamp | None = ...,
            stream_revision: _builtins.int | None = ...,
            position: Global___ReadResp.Position | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_position", b"_position", "_stream_revision", b"_stream_revision", "position", b"position", "stream_revision", b"stream_revision", "timestamp", b"timestamp"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_position", b"_position", "_stream_revision", b"_stream_revision", "position", b"position", "stream_revision", b"stream_revision", "timestamp", b"timestamp"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__position: _TypeAlias = _typing.Literal["position"]  # noqa: Y015
        _WhichOneofArgType__position: _TypeAlias = _typing.Literal["_position", b"_position"]  # noqa: Y015
        _WhichOneofReturnType__stream_revision: _TypeAlias = _typing.Literal["stream_revision"]  # noqa: Y015
        _WhichOneofArgType__stream_revision: _TypeAlias = _typing.Literal["_stream_revision", b"_stream_revision"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__position) -> _WhichOneofReturnType__position | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__stream_revision) -> _WhichOneofReturnType__stream_revision | None: ...

    @_typing.final
    class FellBehind(_message.Message):
        """The $all or stream subscription has fallen back into catchup mode and is no longer live."""

        DESCRIPTOR: _descriptor.Descriptor

        TIMESTAMP_FIELD_NUMBER: _builtins.int
        STREAM_REVISION_FIELD_NUMBER: _builtins.int
        POSITION_FIELD_NUMBER: _builtins.int
        stream_revision: _builtins.int
        """Checkpoint for resuming a stream subscription.
        For stream subscriptions it is populated unless the stream is empty.
        For $all subscriptions it is not populated.
        """
        @_builtins.property
        def timestamp(self) -> _timestamp_pb2.Timestamp:
            """Current time in the server when the subscription fell behind"""

        @_builtins.property
        def position(self) -> Global___ReadResp.Position:
            """Checkpoint for resuming a $all subscription.
            For stream subscriptions it is not populated.
            For $all subscriptions it is populated unless the database is empty.
            """

        def __init__(
            self,
            *,
            timestamp: _timestamp_pb2.Timestamp | None = ...,
            stream_revision: _builtins.int | None = ...,
            position: Global___ReadResp.Position | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_position", b"_position", "_stream_revision", b"_stream_revision", "position", b"position", "stream_revision", b"stream_revision", "timestamp", b"timestamp"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_position", b"_position", "_stream_revision", b"_stream_revision", "position", b"position", "stream_revision", b"stream_revision", "timestamp", b"timestamp"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__position: _TypeAlias = _typing.Literal["position"]  # noqa: Y015
        _WhichOneofArgType__position: _TypeAlias = _typing.Literal["_position", b"_position"]  # noqa: Y015
        _WhichOneofReturnType__stream_revision: _TypeAlias = _typing.Literal["stream_revision"]  # noqa: Y015
        _WhichOneofArgType__stream_revision: _TypeAlias = _typing.Literal["_stream_revision", b"_stream_revision"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__position) -> _WhichOneofReturnType__position | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__stream_revision) -> _WhichOneofReturnType__stream_revision | None: ...

    @_typing.final
    class Position(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        COMMIT_POSITION_FIELD_NUMBER: _builtins.int
        PREPARE_POSITION_FIELD_NUMBER: _builtins.int
        commit_position: _builtins.int
        prepare_position: _builtins.int
        def __init__(
            self,
            *,
            commit_position: _builtins.int = ...,
            prepare_position: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["commit_position", b"commit_position", "prepare_position", b"prepare_position"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class StreamNotFound(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STREAM_IDENTIFIER_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def stream_identifier(self) -> _shared_pb2.StreamIdentifier: ...
        def __init__(
            self,
            *,
            stream_identifier: _shared_pb2.StreamIdentifier | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["stream_identifier", b"stream_identifier"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["stream_identifier", b"stream_identifier"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    EVENT_FIELD_NUMBER: _builtins.int
    CONFIRMATION_FIELD_NUMBER: _builtins.int
    CHECKPOINT_FIELD_NUMBER: _builtins.int
    STREAM_NOT_FOUND_FIELD_NUMBER: _builtins.int
    FIRST_STREAM_POSITION_FIELD_NUMBER: _builtins.int
    LAST_STREAM_POSITION_FIELD_NUMBER: _builtins.int
    LAST_ALL_STREAM_POSITION_FIELD_NUMBER: _builtins.int
    CAUGHT_UP_FIELD_NUMBER: _builtins.int
    FELL_BEHIND_FIELD_NUMBER: _builtins.int
    first_stream_position: _builtins.int
    last_stream_position: _builtins.int
    @_builtins.property
    def event(self) -> Global___ReadResp.ReadEvent: ...
    @_builtins.property
    def confirmation(self) -> Global___ReadResp.SubscriptionConfirmation: ...
    @_builtins.property
    def checkpoint(self) -> Global___ReadResp.Checkpoint: ...
    @_builtins.property
    def stream_not_found(self) -> Global___ReadResp.StreamNotFound: ...
    @_builtins.property
    def last_all_stream_position(self) -> _shared_pb2.AllStreamPosition: ...
    @_builtins.property
    def caught_up(self) -> Global___ReadResp.CaughtUp: ...
    @_builtins.property
    def fell_behind(self) -> Global___ReadResp.FellBehind: ...
    def __init__(
        self,
        *,
        event: Global___ReadResp.ReadEvent | None = ...,
        confirmation: Global___ReadResp.SubscriptionConfirmation | None = ...,
        checkpoint: Global___ReadResp.Checkpoint | None = ...,
        stream_not_found: Global___ReadResp.StreamNotFound | None = ...,
        first_stream_position: _builtins.int = ...,
        last_stream_position: _builtins.int = ...,
        last_all_stream_position: _shared_pb2.AllStreamPosition | None = ...,
        caught_up: Global___ReadResp.CaughtUp | None = ...,
        fell_behind: Global___ReadResp.FellBehind | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["caught_up", b"caught_up", "checkpoint", b"checkpoint", "confirmation", b"confirmation", "content", b"content", "event", b"event", "fell_behind", b"fell_behind", "first_stream_position", b"first_stream_position", "last_all_stream_position", b"last_all_stream_position", "last_stream_position", b"last_stream_position", "stream_not_found", b"stream_not_found"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["caught_up", b"caught_up", "checkpoint", b"checkpoint", "confirmation", b"confirmation", "content", b"content", "event", b"event", "fell_behind", b"fell_behind", "first_stream_position", b"first_stream_position", "last_all_stream_position", b"last_all_stream_position", "last_stream_position", b"last_stream_position", "stream_not_found", b"stream_not_found"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_content: _TypeAlias = _typing.Literal["event", "confirmation", "checkpoint", "stream_not_found", "first_stream_position", "last_stream_position", "last_all_stream_position", "caught_up", "fell_behind"]  # noqa: Y015
    _WhichOneofArgType_content: _TypeAlias = _typing.Literal["content", b"content"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_content) -> _WhichOneofReturnType_content | None: ...

Global___ReadResp: _TypeAlias = ReadResp  # noqa: Y015

@_typing.final
class AppendReq(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Options(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STREAM_IDENTIFIER_FIELD_NUMBER: _builtins.int
        REVISION_FIELD_NUMBER: _builtins.int
        NO_STREAM_FIELD_NUMBER: _builtins.int
        ANY_FIELD_NUMBER: _builtins.int
        STREAM_EXISTS_FIELD_NUMBER: _builtins.int
        revision: _builtins.int
        @_builtins.property
        def stream_identifier(self) -> _shared_pb2.StreamIdentifier: ...
        @_builtins.property
        def no_stream(self) -> _shared_pb2.Empty: ...
        @_builtins.property
        def any(self) -> _shared_pb2.Empty: ...
        @_builtins.property
        def stream_exists(self) -> _shared_pb2.Empty: ...
        def __init__(
            self,
            *,
            stream_identifier: _shared_pb2.StreamIdentifier | None = ...,
            revision: _builtins.int = ...,
            no_stream: _shared_pb2.Empty | None = ...,
            any: _shared_pb2.Empty | None = ...,
            stream_exists: _shared_pb2.Empty | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["any", b"any", "expected_stream_revision", b"expected_stream_revision", "no_stream", b"no_stream", "revision", b"revision", "stream_exists", b"stream_exists", "stream_identifier", b"stream_identifier"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["any", b"any", "expected_stream_revision", b"expected_stream_revision", "no_stream", b"no_stream", "revision", b"revision", "stream_exists", b"stream_exists", "stream_identifier", b"stream_identifier"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_expected_stream_revision: _TypeAlias = _typing.Literal["revision", "no_stream", "any", "stream_exists"]  # noqa: Y015
        _WhichOneofArgType_expected_stream_revision: _TypeAlias = _typing.Literal["expected_stream_revision", b"expected_stream_revision"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_expected_stream_revision) -> _WhichOneofReturnType_expected_stream_revision | None: ...

    @_typing.final
    class ProposedMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class MetadataEntry(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            KEY_FIELD_NUMBER: _builtins.int
            VALUE_FIELD_NUMBER: _builtins.int
            key: _builtins.str
            value: _builtins.str
            def __init__(
                self,
                *,
                key: _builtins.str = ...,
                value: _builtins.str = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        ID_FIELD_NUMBER: _builtins.int
        METADATA_FIELD_NUMBER: _builtins.int
        CUSTOM_METADATA_FIELD_NUMBER: _builtins.int
        DATA_FIELD_NUMBER: _builtins.int
        custom_metadata: _builtins.bytes
        data: _builtins.bytes
        @_builtins.property
        def id(self) -> _shared_pb2.UUID: ...
        @_builtins.property
        def metadata(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
        def __init__(
            self,
            *,
            id: _shared_pb2.UUID | None = ...,
            metadata: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
            custom_metadata: _builtins.bytes = ...,
            data: _builtins.bytes = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["custom_metadata", b"custom_metadata", "data", b"data", "id", b"id", "metadata", b"metadata"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    OPTIONS_FIELD_NUMBER: _builtins.int
    PROPOSED_MESSAGE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def options(self) -> Global___AppendReq.Options: ...
    @_builtins.property
    def proposed_message(self) -> Global___AppendReq.ProposedMessage: ...
    def __init__(
        self,
        *,
        options: Global___AppendReq.Options | None = ...,
        proposed_message: Global___AppendReq.ProposedMessage | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "options", b"options", "proposed_message", b"proposed_message"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "options", b"options", "proposed_message", b"proposed_message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_content: _TypeAlias = _typing.Literal["options", "proposed_message"]  # noqa: Y015
    _WhichOneofArgType_content: _TypeAlias = _typing.Literal["content", b"content"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_content) -> _WhichOneofReturnType_content | None: ...

Global___AppendReq: _TypeAlias = AppendReq  # noqa: Y015

@_typing.final
class AppendResp(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Position(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        COMMIT_POSITION_FIELD_NUMBER: _builtins.int
        PREPARE_POSITION_FIELD_NUMBER: _builtins.int
        commit_position: _builtins.int
        prepare_position: _builtins.int
        def __init__(
            self,
            *,
            commit_position: _builtins.int = ...,
            prepare_position: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["commit_position", b"commit_position", "prepare_position", b"prepare_position"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class Success(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        CURRENT_REVISION_FIELD_NUMBER: _builtins.int
        NO_STREAM_FIELD_NUMBER: _builtins.int
        POSITION_FIELD_NUMBER: _builtins.int
        NO_POSITION_FIELD_NUMBER: _builtins.int
        current_revision: _builtins.int
        @_builtins.property
        def no_stream(self) -> _shared_pb2.Empty: ...
        @_builtins.property
        def position(self) -> Global___AppendResp.Position: ...
        @_builtins.property
        def no_position(self) -> _shared_pb2.Empty: ...
        def __init__(
            self,
            *,
            current_revision: _builtins.int = ...,
            no_stream: _shared_pb2.Empty | None = ...,
            position: Global___AppendResp.Position | None = ...,
            no_position: _shared_pb2.Empty | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["current_revision", b"current_revision", "current_revision_option", b"current_revision_option", "no_position", b"no_position", "no_stream", b"no_stream", "position", b"position", "position_option", b"position_option"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["current_revision", b"current_revision", "current_revision_option", b"current_revision_option", "no_position", b"no_position", "no_stream", b"no_stream", "position", b"position", "position_option", b"position_option"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_current_revision_option: _TypeAlias = _typing.Literal["current_revision", "no_stream"]  # noqa: Y015
        _WhichOneofArgType_current_revision_option: _TypeAlias = _typing.Literal["current_revision_option", b"current_revision_option"]  # noqa: Y015
        _WhichOneofReturnType_position_option: _TypeAlias = _typing.Literal["position", "no_position"]  # noqa: Y015
        _WhichOneofArgType_position_option: _TypeAlias = _typing.Literal["position_option", b"position_option"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType_current_revision_option) -> _WhichOneofReturnType_current_revision_option | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType_position_option) -> _WhichOneofReturnType_position_option | None: ...

    @_typing.final
    class WrongExpectedVersion(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        CURRENT_REVISION_20_6_0_FIELD_NUMBER: _builtins.int
        NO_STREAM_20_6_0_FIELD_NUMBER: _builtins.int
        EXPECTED_REVISION_20_6_0_FIELD_NUMBER: _builtins.int
        ANY_20_6_0_FIELD_NUMBER: _builtins.int
        STREAM_EXISTS_20_6_0_FIELD_NUMBER: _builtins.int
        CURRENT_REVISION_FIELD_NUMBER: _builtins.int
        CURRENT_NO_STREAM_FIELD_NUMBER: _builtins.int
        EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
        EXPECTED_ANY_FIELD_NUMBER: _builtins.int
        EXPECTED_STREAM_EXISTS_FIELD_NUMBER: _builtins.int
        EXPECTED_NO_STREAM_FIELD_NUMBER: _builtins.int
        current_revision_20_6_0: _builtins.int
        expected_revision_20_6_0: _builtins.int
        current_revision: _builtins.int
        expected_revision: _builtins.int
        @_builtins.property
        def no_stream_20_6_0(self) -> _shared_pb2.Empty: ...
        @_builtins.property
        def any_20_6_0(self) -> _shared_pb2.Empty: ...
        @_builtins.property
        def stream_exists_20_6_0(self) -> _shared_pb2.Empty: ...
        @_builtins.property
        def current_no_stream(self) -> _shared_pb2.Empty: ...
        @_builtins.property
        def expected_any(self) -> _shared_pb2.Empty: ...
        @_builtins.property
        def expected_stream_exists(self) -> _shared_pb2.Empty: ...
        @_builtins.property
        def expected_no_stream(self) -> _shared_pb2.Empty: ...
        def __init__(
            self,
            *,
            current_revision_20_6_0: _builtins.int = ...,
            no_stream_20_6_0: _shared_pb2.Empty | None = ...,
            expected_revision_20_6_0: _builtins.int = ...,
            any_20_6_0: _shared_pb2.Empty | None = ...,
            stream_exists_20_6_0: _shared_pb2.Empty | None = ...,
            current_revision: _builtins.int = ...,
            current_no_stream: _shared_pb2.Empty | None = ...,
            expected_revision: _builtins.int = ...,
            expected_any: _shared_pb2.Empty | None = ...,
            expected_stream_exists: _shared_pb2.Empty | None = ...,
            expected_no_stream: _shared_pb2.Empty | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["any_20_6_0", b"any_20_6_0", "current_no_stream", b"current_no_stream", "current_revision", b"current_revision", "current_revision_20_6_0", b"current_revision_20_6_0", "current_revision_option", b"current_revision_option", "current_revision_option_20_6_0", b"current_revision_option_20_6_0", "expected_any", b"expected_any", "expected_no_stream", b"expected_no_stream", "expected_revision", b"expected_revision", "expected_revision_20_6_0", b"expected_revision_20_6_0", "expected_revision_option", b"expected_revision_option", "expected_revision_option_20_6_0", b"expected_revision_option_20_6_0", "expected_stream_exists", b"expected_stream_exists", "no_stream_20_6_0", b"no_stream_20_6_0", "stream_exists_20_6_0", b"stream_exists_20_6_0"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["any_20_6_0", b"any_20_6_0", "current_no_stream", b"current_no_stream", "current_revision", b"current_revision", "current_revision_20_6_0", b"current_revision_20_6_0", "current_revision_option", b"current_revision_option", "current_revision_option_20_6_0", b"current_revision_option_20_6_0", "expected_any", b"expected_any", "expected_no_stream", b"expected_no_stream", "expected_revision", b"expected_revision", "expected_revision_20_6_0", b"expected_revision_20_6_0", "expected_revision_option", b"expected_revision_option", "expected_revision_option_20_6_0", b"expected_revision_option_20_6_0", "expected_stream_exists", b"expected_stream_exists", "no_stream_20_6_0", b"no_stream_20_6_0", "stream_exists_20_6_0", b"stream_exists_20_6_0"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_current_revision_option: _TypeAlias = _typing.Literal["current_revision", "current_no_stream"]  # noqa: Y015
        _WhichOneofArgType_current_revision_option: _TypeAlias = _typing.Literal["current_revision_option", b"current_revision_option"]  # noqa: Y015
        _WhichOneofReturnType_current_revision_option_20_6_0: _TypeAlias = _typing.Literal["current_revision_20_6_0", "no_stream_20_6_0"]  # noqa: Y015
        _WhichOneofArgType_current_revision_option_20_6_0: _TypeAlias = _typing.Literal["current_revision_option_20_6_0", b"current_revision_option_20_6_0"]  # noqa: Y015
        _WhichOneofReturnType_expected_revision_option: _TypeAlias = _typing.Literal["expected_revision", "expected_any", "expected_stream_exists", "expected_no_stream"]  # noqa: Y015
        _WhichOneofArgType_expected_revision_option: _TypeAlias = _typing.Literal["expected_revision_option", b"expected_revision_option"]  # noqa: Y015
        _WhichOneofReturnType_expected_revision_option_20_6_0: _TypeAlias = _typing.Literal["expected_revision_20_6_0", "any_20_6_0", "stream_exists_20_6_0"]  # noqa: Y015
        _WhichOneofArgType_expected_revision_option_20_6_0: _TypeAlias = _typing.Literal["expected_revision_option_20_6_0", b"expected_revision_option_20_6_0"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType_current_revision_option) -> _WhichOneofReturnType_current_revision_option | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType_current_revision_option_20_6_0) -> _WhichOneofReturnType_current_revision_option_20_6_0 | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType_expected_revision_option) -> _WhichOneofReturnType_expected_revision_option | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType_expected_revision_option_20_6_0) -> _WhichOneofReturnType_expected_revision_option_20_6_0 | None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    WRONG_EXPECTED_VERSION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> Global___AppendResp.Success: ...
    @_builtins.property
    def wrong_expected_version(self) -> Global___AppendResp.WrongExpectedVersion: ...
    def __init__(
        self,
        *,
        success: Global___AppendResp.Success | None = ...,
        wrong_expected_version: Global___AppendResp.WrongExpectedVersion | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["result", b"result", "success", b"success", "wrong_expected_version", b"wrong_expected_version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["result", b"result", "success", b"success", "wrong_expected_version", b"wrong_expected_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_result: _TypeAlias = _typing.Literal["success", "wrong_expected_version"]  # noqa: Y015
    _WhichOneofArgType_result: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_result) -> _WhichOneofReturnType_result | None: ...

Global___AppendResp: _TypeAlias = AppendResp  # noqa: Y015

@_typing.final
class BatchAppendReq(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Options(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STREAM_IDENTIFIER_FIELD_NUMBER: _builtins.int
        STREAM_POSITION_FIELD_NUMBER: _builtins.int
        NO_STREAM_FIELD_NUMBER: _builtins.int
        ANY_FIELD_NUMBER: _builtins.int
        STREAM_EXISTS_FIELD_NUMBER: _builtins.int
        DEADLINE_21_10_0_FIELD_NUMBER: _builtins.int
        DEADLINE_FIELD_NUMBER: _builtins.int
        stream_position: _builtins.int
        @_builtins.property
        def stream_identifier(self) -> _shared_pb2.StreamIdentifier: ...
        @_builtins.property
        def no_stream(self) -> _empty_pb2.Empty: ...
        @_builtins.property
        def any(self) -> _empty_pb2.Empty: ...
        @_builtins.property
        def stream_exists(self) -> _empty_pb2.Empty: ...
        @_builtins.property
        def deadline_21_10_0(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def deadline(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            stream_identifier: _shared_pb2.StreamIdentifier | None = ...,
            stream_position: _builtins.int = ...,
            no_stream: _empty_pb2.Empty | None = ...,
            any: _empty_pb2.Empty | None = ...,
            stream_exists: _empty_pb2.Empty | None = ...,
            deadline_21_10_0: _timestamp_pb2.Timestamp | None = ...,
            deadline: _duration_pb2.Duration | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["any", b"any", "deadline", b"deadline", "deadline_21_10_0", b"deadline_21_10_0", "deadline_option", b"deadline_option", "expected_stream_position", b"expected_stream_position", "no_stream", b"no_stream", "stream_exists", b"stream_exists", "stream_identifier", b"stream_identifier", "stream_position", b"stream_position"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["any", b"any", "deadline", b"deadline", "deadline_21_10_0", b"deadline_21_10_0", "deadline_option", b"deadline_option", "expected_stream_position", b"expected_stream_position", "no_stream", b"no_stream", "stream_exists", b"stream_exists", "stream_identifier", b"stream_identifier", "stream_position", b"stream_position"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_deadline_option: _TypeAlias = _typing.Literal["deadline_21_10_0", "deadline"]  # noqa: Y015
        _WhichOneofArgType_deadline_option: _TypeAlias = _typing.Literal["deadline_option", b"deadline_option"]  # noqa: Y015
        _WhichOneofReturnType_expected_stream_position: _TypeAlias = _typing.Literal["stream_position", "no_stream", "any", "stream_exists"]  # noqa: Y015
        _WhichOneofArgType_expected_stream_position: _TypeAlias = _typing.Literal["expected_stream_position", b"expected_stream_position"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType_deadline_option) -> _WhichOneofReturnType_deadline_option | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType_expected_stream_position) -> _WhichOneofReturnType_expected_stream_position | None: ...

    @_typing.final
    class ProposedMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class MetadataEntry(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            KEY_FIELD_NUMBER: _builtins.int
            VALUE_FIELD_NUMBER: _builtins.int
            key: _builtins.str
            value: _builtins.str
            def __init__(
                self,
                *,
                key: _builtins.str = ...,
                value: _builtins.str = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        ID_FIELD_NUMBER: _builtins.int
        METADATA_FIELD_NUMBER: _builtins.int
        CUSTOM_METADATA_FIELD_NUMBER: _builtins.int
        DATA_FIELD_NUMBER: _builtins.int
        custom_metadata: _builtins.bytes
        data: _builtins.bytes
        @_builtins.property
        def id(self) -> _shared_pb2.UUID: ...
        @_builtins.property
        def metadata(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
        def __init__(
            self,
            *,
            id: _shared_pb2.UUID | None = ...,
            metadata: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
            custom_metadata: _builtins.bytes = ...,
            data: _builtins.bytes = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["custom_metadata", b"custom_metadata", "data", b"data", "id", b"id", "metadata", b"metadata"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    CORRELATION_ID_FIELD_NUMBER: _builtins.int
    OPTIONS_FIELD_NUMBER: _builtins.int
    PROPOSED_MESSAGES_FIELD_NUMBER: _builtins.int
    IS_FINAL_FIELD_NUMBER: _builtins.int
    is_final: _builtins.bool
    @_builtins.property
    def correlation_id(self) -> _shared_pb2.UUID: ...
    @_builtins.property
    def options(self) -> Global___BatchAppendReq.Options: ...
    @_builtins.property
    def proposed_messages(self) -> _containers.RepeatedCompositeFieldContainer[Global___BatchAppendReq.ProposedMessage]: ...
    def __init__(
        self,
        *,
        correlation_id: _shared_pb2.UUID | None = ...,
        options: Global___BatchAppendReq.Options | None = ...,
        proposed_messages: _abc.Iterable[Global___BatchAppendReq.ProposedMessage] | None = ...,
        is_final: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["correlation_id", b"correlation_id", "options", b"options"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["correlation_id", b"correlation_id", "is_final", b"is_final", "options", b"options", "proposed_messages", b"proposed_messages"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BatchAppendReq: _TypeAlias = BatchAppendReq  # noqa: Y015

@_typing.final
class BatchAppendResp(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Success(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        CURRENT_REVISION_FIELD_NUMBER: _builtins.int
        NO_STREAM_FIELD_NUMBER: _builtins.int
        POSITION_FIELD_NUMBER: _builtins.int
        NO_POSITION_FIELD_NUMBER: _builtins.int
        current_revision: _builtins.int
        @_builtins.property
        def no_stream(self) -> _empty_pb2.Empty: ...
        @_builtins.property
        def position(self) -> _shared_pb2.AllStreamPosition: ...
        @_builtins.property
        def no_position(self) -> _empty_pb2.Empty: ...
        def __init__(
            self,
            *,
            current_revision: _builtins.int = ...,
            no_stream: _empty_pb2.Empty | None = ...,
            position: _shared_pb2.AllStreamPosition | None = ...,
            no_position: _empty_pb2.Empty | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["current_revision", b"current_revision", "current_revision_option", b"current_revision_option", "no_position", b"no_position", "no_stream", b"no_stream", "position", b"position", "position_option", b"position_option"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["current_revision", b"current_revision", "current_revision_option", b"current_revision_option", "no_position", b"no_position", "no_stream", b"no_stream", "position", b"position", "position_option", b"position_option"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_current_revision_option: _TypeAlias = _typing.Literal["current_revision", "no_stream"]  # noqa: Y015
        _WhichOneofArgType_current_revision_option: _TypeAlias = _typing.Literal["current_revision_option", b"current_revision_option"]  # noqa: Y015
        _WhichOneofReturnType_position_option: _TypeAlias = _typing.Literal["position", "no_position"]  # noqa: Y015
        _WhichOneofArgType_position_option: _TypeAlias = _typing.Literal["position_option", b"position_option"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType_current_revision_option) -> _WhichOneofReturnType_current_revision_option | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType_position_option) -> _WhichOneofReturnType_position_option | None: ...

    CORRELATION_ID_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    STREAM_IDENTIFIER_FIELD_NUMBER: _builtins.int
    STREAM_POSITION_FIELD_NUMBER: _builtins.int
    NO_STREAM_FIELD_NUMBER: _builtins.int
    ANY_FIELD_NUMBER: _builtins.int
    STREAM_EXISTS_FIELD_NUMBER: _builtins.int
    stream_position: _builtins.int
    @_builtins.property
    def correlation_id(self) -> _shared_pb2.UUID: ...
    @_builtins.property
    def error(self) -> _status_pb2.Status: ...
    @_builtins.property
    def success(self) -> Global___BatchAppendResp.Success: ...
    @_builtins.property
    def stream_identifier(self) -> _shared_pb2.StreamIdentifier: ...
    @_builtins.property
    def no_stream(self) -> _empty_pb2.Empty: ...
    @_builtins.property
    def any(self) -> _empty_pb2.Empty: ...
    @_builtins.property
    def stream_exists(self) -> _empty_pb2.Empty: ...
    def __init__(
        self,
        *,
        correlation_id: _shared_pb2.UUID | None = ...,
        error: _status_pb2.Status | None = ...,
        success: Global___BatchAppendResp.Success | None = ...,
        stream_identifier: _shared_pb2.StreamIdentifier | None = ...,
        stream_position: _builtins.int = ...,
        no_stream: _empty_pb2.Empty | None = ...,
        any: _empty_pb2.Empty | None = ...,
        stream_exists: _empty_pb2.Empty | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["any", b"any", "correlation_id", b"correlation_id", "error", b"error", "expected_stream_position", b"expected_stream_position", "no_stream", b"no_stream", "result", b"result", "stream_exists", b"stream_exists", "stream_identifier", b"stream_identifier", "stream_position", b"stream_position", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["any", b"any", "correlation_id", b"correlation_id", "error", b"error", "expected_stream_position", b"expected_stream_position", "no_stream", b"no_stream", "result", b"result", "stream_exists", b"stream_exists", "stream_identifier", b"stream_identifier", "stream_position", b"stream_position", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_expected_stream_position: _TypeAlias = _typing.Literal["stream_position", "no_stream", "any", "stream_exists"]  # noqa: Y015
    _WhichOneofArgType_expected_stream_position: _TypeAlias = _typing.Literal["expected_stream_position", b"expected_stream_position"]  # noqa: Y015
    _WhichOneofReturnType_result: _TypeAlias = _typing.Literal["error", "success"]  # noqa: Y015
    _WhichOneofArgType_result: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType_expected_stream_position) -> _WhichOneofReturnType_expected_stream_position | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType_result) -> _WhichOneofReturnType_result | None: ...

Global___BatchAppendResp: _TypeAlias = BatchAppendResp  # noqa: Y015

@_typing.final
class DeleteReq(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Options(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STREAM_IDENTIFIER_FIELD_NUMBER: _builtins.int
        REVISION_FIELD_NUMBER: _builtins.int
        NO_STREAM_FIELD_NUMBER: _builtins.int
        ANY_FIELD_NUMBER: _builtins.int
        STREAM_EXISTS_FIELD_NUMBER: _builtins.int
        revision: _builtins.int
        @_builtins.property
        def stream_identifier(self) -> _shared_pb2.StreamIdentifier: ...
        @_builtins.property
        def no_stream(self) -> _shared_pb2.Empty: ...
        @_builtins.property
        def any(self) -> _shared_pb2.Empty: ...
        @_builtins.property
        def stream_exists(self) -> _shared_pb2.Empty: ...
        def __init__(
            self,
            *,
            stream_identifier: _shared_pb2.StreamIdentifier | None = ...,
            revision: _builtins.int = ...,
            no_stream: _shared_pb2.Empty | None = ...,
            any: _shared_pb2.Empty | None = ...,
            stream_exists: _shared_pb2.Empty | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["any", b"any", "expected_stream_revision", b"expected_stream_revision", "no_stream", b"no_stream", "revision", b"revision", "stream_exists", b"stream_exists", "stream_identifier", b"stream_identifier"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["any", b"any", "expected_stream_revision", b"expected_stream_revision", "no_stream", b"no_stream", "revision", b"revision", "stream_exists", b"stream_exists", "stream_identifier", b"stream_identifier"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_expected_stream_revision: _TypeAlias = _typing.Literal["revision", "no_stream", "any", "stream_exists"]  # noqa: Y015
        _WhichOneofArgType_expected_stream_revision: _TypeAlias = _typing.Literal["expected_stream_revision", b"expected_stream_revision"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_expected_stream_revision) -> _WhichOneofReturnType_expected_stream_revision | None: ...

    OPTIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def options(self) -> Global___DeleteReq.Options: ...
    def __init__(
        self,
        *,
        options: Global___DeleteReq.Options | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["options", b"options"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["options", b"options"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteReq: _TypeAlias = DeleteReq  # noqa: Y015

@_typing.final
class DeleteResp(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Position(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        COMMIT_POSITION_FIELD_NUMBER: _builtins.int
        PREPARE_POSITION_FIELD_NUMBER: _builtins.int
        commit_position: _builtins.int
        prepare_position: _builtins.int
        def __init__(
            self,
            *,
            commit_position: _builtins.int = ...,
            prepare_position: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["commit_position", b"commit_position", "prepare_position", b"prepare_position"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    POSITION_FIELD_NUMBER: _builtins.int
    NO_POSITION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def position(self) -> Global___DeleteResp.Position: ...
    @_builtins.property
    def no_position(self) -> _shared_pb2.Empty: ...
    def __init__(
        self,
        *,
        position: Global___DeleteResp.Position | None = ...,
        no_position: _shared_pb2.Empty | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["no_position", b"no_position", "position", b"position", "position_option", b"position_option"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["no_position", b"no_position", "position", b"position", "position_option", b"position_option"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_position_option: _TypeAlias = _typing.Literal["position", "no_position"]  # noqa: Y015
    _WhichOneofArgType_position_option: _TypeAlias = _typing.Literal["position_option", b"position_option"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_position_option) -> _WhichOneofReturnType_position_option | None: ...

Global___DeleteResp: _TypeAlias = DeleteResp  # noqa: Y015

@_typing.final
class TombstoneReq(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Options(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STREAM_IDENTIFIER_FIELD_NUMBER: _builtins.int
        REVISION_FIELD_NUMBER: _builtins.int
        NO_STREAM_FIELD_NUMBER: _builtins.int
        ANY_FIELD_NUMBER: _builtins.int
        STREAM_EXISTS_FIELD_NUMBER: _builtins.int
        revision: _builtins.int
        @_builtins.property
        def stream_identifier(self) -> _shared_pb2.StreamIdentifier: ...
        @_builtins.property
        def no_stream(self) -> _shared_pb2.Empty: ...
        @_builtins.property
        def any(self) -> _shared_pb2.Empty: ...
        @_builtins.property
        def stream_exists(self) -> _shared_pb2.Empty: ...
        def __init__(
            self,
            *,
            stream_identifier: _shared_pb2.StreamIdentifier | None = ...,
            revision: _builtins.int = ...,
            no_stream: _shared_pb2.Empty | None = ...,
            any: _shared_pb2.Empty | None = ...,
            stream_exists: _shared_pb2.Empty | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["any", b"any", "expected_stream_revision", b"expected_stream_revision", "no_stream", b"no_stream", "revision", b"revision", "stream_exists", b"stream_exists", "stream_identifier", b"stream_identifier"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["any", b"any", "expected_stream_revision", b"expected_stream_revision", "no_stream", b"no_stream", "revision", b"revision", "stream_exists", b"stream_exists", "stream_identifier", b"stream_identifier"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_expected_stream_revision: _TypeAlias = _typing.Literal["revision", "no_stream", "any", "stream_exists"]  # noqa: Y015
        _WhichOneofArgType_expected_stream_revision: _TypeAlias = _typing.Literal["expected_stream_revision", b"expected_stream_revision"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_expected_stream_revision) -> _WhichOneofReturnType_expected_stream_revision | None: ...

    OPTIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def options(self) -> Global___TombstoneReq.Options: ...
    def __init__(
        self,
        *,
        options: Global___TombstoneReq.Options | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["options", b"options"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["options", b"options"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TombstoneReq: _TypeAlias = TombstoneReq  # noqa: Y015

@_typing.final
class TombstoneResp(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Position(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        COMMIT_POSITION_FIELD_NUMBER: _builtins.int
        PREPARE_POSITION_FIELD_NUMBER: _builtins.int
        commit_position: _builtins.int
        prepare_position: _builtins.int
        def __init__(
            self,
            *,
            commit_position: _builtins.int = ...,
            prepare_position: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["commit_position", b"commit_position", "prepare_position", b"prepare_position"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    POSITION_FIELD_NUMBER: _builtins.int
    NO_POSITION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def position(self) -> Global___TombstoneResp.Position: ...
    @_builtins.property
    def no_position(self) -> _shared_pb2.Empty: ...
    def __init__(
        self,
        *,
        position: Global___TombstoneResp.Position | None = ...,
        no_position: _shared_pb2.Empty | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["no_position", b"no_position", "position", b"position", "position_option", b"position_option"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["no_position", b"no_position", "position", b"position", "position_option", b"position_option"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_position_option: _TypeAlias = _typing.Literal["position", "no_position"]  # noqa: Y015
    _WhichOneofArgType_position_option: _TypeAlias = _typing.Literal["position_option", b"position_option"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_position_option) -> _WhichOneofReturnType_position_option | None: ...

Global___TombstoneResp: _TypeAlias = TombstoneResp  # noqa: Y015
