"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
******************************************************************************************
This protocol is UNSTABLE in the sense of being subject to change.
******************************************************************************************
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ServerError:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ServerErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ServerError.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNSPECIFIED: _ServerError.ValueType  # 0
    """Default value. This value is not used.
    An error code MUST always be set to a non-zero value.
    If an error code is not explicitly set, it MUST be treated as
    an internal server error (INTERNAL).
    """
    SERVER_ERROR_ACCESS_DENIED: _ServerError.ValueType  # 1
    """Authentication or authorization failure.
    The client lacks valid credentials or sufficient permissions to perform the requested operation.

    Common causes:
    - Missing or invalid authentication tokens
    - Insufficient permissions for the operation
    - Expired credentials

    Client action: Check credentials, verify permissions, and re-authenticate if necessary.
    Not retriable without fixing the underlying authorization issue.
    """
    SERVER_ERROR_BAD_REQUEST: _ServerError.ValueType  # 2
    """The request is malformed or contains invalid data.
    The server cannot process the request due to client error.

    Common causes:
    - Invalid field values (e.g., empty required fields, out-of-range numbers)
    - Malformed data formats
    - Validation failures

    Client action: Fix the request data and retry.
    Not retriable without modifying the request.
    """
    SERVER_ERROR_NOT_LEADER_NODE: _ServerError.ValueType  # 5
    """The server is not the cluster leader and cannot process write operations.
    In a clustered deployment, only the leader node can accept write operations.

    Common causes:
    - Client connected to a follower node
    - Leader election in progress
    - Network partition

    Client action: Redirect the request to the leader node indicated in the error details.
    Retriable after redirecting to the correct leader node.
    """
    SERVER_ERROR_OPERATION_TIMEOUT: _ServerError.ValueType  # 6
    """The operation did not complete within the configured timeout period.

    Common causes:
    - Slow disk I/O during writes
    - Cluster consensus delays
    - Network latency
    - Heavy server load

    Client action: Retry with exponential backoff. Consider increasing timeout values.
    Retriable - the operation may succeed on retry.
    """
    SERVER_ERROR_SERVER_NOT_READY: _ServerError.ValueType  # 7
    """The server is starting up or shutting down and cannot process requests.

    Common causes:
    - Server is initializing (loading indexes, recovering state)
    - Server is performing graceful shutdown
    - Server is performing maintenance operations

    Client action: Retry with exponential backoff. Wait for server to become ready.
    Retriable - the server will become available after initialization completes.
    """
    SERVER_ERROR_SERVER_OVERLOADED: _ServerError.ValueType  # 8
    """The server is temporarily overloaded and cannot accept more requests.
    This is a backpressure mechanism to prevent server overload.

    Common causes:
    - Too many concurrent requests
    - Resource exhaustion (CPU, memory, disk I/O)
    - Rate limiting triggered

    Client action: Retry with exponential backoff. Reduce request rate.
    Retriable - the server may accept requests after load decreases.
    """
    SERVER_ERROR_SERVER_MALFUNCTION: _ServerError.ValueType  # 9
    """An internal server error occurred.
    This indicates a bug or unexpected condition in the server.

    Common causes:
    - Unhandled exceptions
    - Assertion failures
    - Corrupted internal state
    - Programming errors

    Client action: Report to server administrators with request details.
    May be retriable, but likely indicates a server-side issue requiring investigation.
    """

class ServerError(_ServerError, metaclass=_ServerErrorEnumTypeWrapper):
    """The canonical server error codes for the Kurrent Platform gRPC APIs.
    These errors represent common failure modes across all Kurrent services.
    """

UNSPECIFIED: ServerError.ValueType  # 0
"""Default value. This value is not used.
An error code MUST always be set to a non-zero value.
If an error code is not explicitly set, it MUST be treated as
an internal server error (INTERNAL).
"""
SERVER_ERROR_ACCESS_DENIED: ServerError.ValueType  # 1
"""Authentication or authorization failure.
The client lacks valid credentials or sufficient permissions to perform the requested operation.

Common causes:
- Missing or invalid authentication tokens
- Insufficient permissions for the operation
- Expired credentials

Client action: Check credentials, verify permissions, and re-authenticate if necessary.
Not retriable without fixing the underlying authorization issue.
"""
SERVER_ERROR_BAD_REQUEST: ServerError.ValueType  # 2
"""The request is malformed or contains invalid data.
The server cannot process the request due to client error.

Common causes:
- Invalid field values (e.g., empty required fields, out-of-range numbers)
- Malformed data formats
- Validation failures

Client action: Fix the request data and retry.
Not retriable without modifying the request.
"""
SERVER_ERROR_NOT_LEADER_NODE: ServerError.ValueType  # 5
"""The server is not the cluster leader and cannot process write operations.
In a clustered deployment, only the leader node can accept write operations.

Common causes:
- Client connected to a follower node
- Leader election in progress
- Network partition

Client action: Redirect the request to the leader node indicated in the error details.
Retriable after redirecting to the correct leader node.
"""
SERVER_ERROR_OPERATION_TIMEOUT: ServerError.ValueType  # 6
"""The operation did not complete within the configured timeout period.

Common causes:
- Slow disk I/O during writes
- Cluster consensus delays
- Network latency
- Heavy server load

Client action: Retry with exponential backoff. Consider increasing timeout values.
Retriable - the operation may succeed on retry.
"""
SERVER_ERROR_SERVER_NOT_READY: ServerError.ValueType  # 7
"""The server is starting up or shutting down and cannot process requests.

Common causes:
- Server is initializing (loading indexes, recovering state)
- Server is performing graceful shutdown
- Server is performing maintenance operations

Client action: Retry with exponential backoff. Wait for server to become ready.
Retriable - the server will become available after initialization completes.
"""
SERVER_ERROR_SERVER_OVERLOADED: ServerError.ValueType  # 8
"""The server is temporarily overloaded and cannot accept more requests.
This is a backpressure mechanism to prevent server overload.

Common causes:
- Too many concurrent requests
- Resource exhaustion (CPU, memory, disk I/O)
- Rate limiting triggered

Client action: Retry with exponential backoff. Reduce request rate.
Retriable - the server may accept requests after load decreases.
"""
SERVER_ERROR_SERVER_MALFUNCTION: ServerError.ValueType  # 9
"""An internal server error occurred.
This indicates a bug or unexpected condition in the server.

Common causes:
- Unhandled exceptions
- Assertion failures
- Corrupted internal state
- Programming errors

Client action: Report to server administrators with request details.
May be retriable, but likely indicates a server-side issue requiring investigation.
"""
global___ServerError = ServerError

@typing.final
class AccessDeniedErrorDetails(google.protobuf.message.Message):
    """Details for ACCESS_DENIED errors."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPERATION_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    PERMISSION_FIELD_NUMBER: builtins.int
    operation: builtins.str
    """The friendly name of the operation that was denied."""
    username: builtins.str
    """The username of the user who was denied access."""
    permission: builtins.str
    """The permission that was required for this operation."""
    def __init__(
        self,
        *,
        operation: builtins.str = ...,
        username: builtins.str | None = ...,
        permission: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_permission", b"_permission", "_username", b"_username", "permission", b"permission", "username", b"username"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_permission", b"_permission", "_username", b"_username", "operation", b"operation", "permission", b"permission", "username", b"username"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_permission", b"_permission"]) -> typing.Literal["permission"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_username", b"_username"]) -> typing.Literal["username"] | None: ...

global___AccessDeniedErrorDetails = AccessDeniedErrorDetails

@typing.final
class NotLeaderNodeErrorDetails(google.protobuf.message.Message):
    """Details for NOT_LEADER_NODE errors."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class NodeInfo(google.protobuf.message.Message):
        """Information about a cluster node."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        HOST_FIELD_NUMBER: builtins.int
        PORT_FIELD_NUMBER: builtins.int
        NODE_ID_FIELD_NUMBER: builtins.int
        host: builtins.str
        """The hostname or IP address of the node."""
        port: builtins.int
        """The gRPC port of the node."""
        node_id: builtins.str
        """The unique instance ID of the node."""
        def __init__(
            self,
            *,
            host: builtins.str = ...,
            port: builtins.int = ...,
            node_id: builtins.str | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_node_id", b"_node_id", "node_id", b"node_id"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_node_id", b"_node_id", "host", b"host", "node_id", b"node_id", "port", b"port"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["_node_id", b"_node_id"]) -> typing.Literal["node_id"] | None: ...

    CURRENT_LEADER_FIELD_NUMBER: builtins.int
    @property
    def current_leader(self) -> global___NotLeaderNodeErrorDetails.NodeInfo:
        """Information about the current cluster leader node."""

    def __init__(
        self,
        *,
        current_leader: global___NotLeaderNodeErrorDetails.NodeInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["current_leader", b"current_leader"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["current_leader", b"current_leader"]) -> None: ...

global___NotLeaderNodeErrorDetails = NotLeaderNodeErrorDetails
