"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
******************************************************************************************
This protocol is UNSTABLE in the sense of being subject to change.
******************************************************************************************
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pb2 as _descriptor_pb2
from google.protobuf import message as _message
from google.protobuf.internal import extension_dict as _extension_dict
from kurrentdbclient.protos.google.rpc import code_pb2 as _code_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ErrorMetadata(_message.Message):
    """ErrorMetadata provides actionable information for error enum values to enable automated
    code generation, documentation, and consistent error handling across the Kurrent platform.

    It was modeled to support a single details type per error code to simplify code generation and
    validation. If multiple detail types are needed for a single error code, consider defining
    separate error codes for each detail type. Or, use a union type (oneof) in the detail message
    to encapsulate multiple detail variants within a single detail message.

    More however DebugInfo and RetryInfo can and should be added to any error regardless of
    this setting, when applicable.

    This annotation is applied to enum values using the google.protobuf.EnumValueOptions
    extension mechanism. It enables:
    - Automatic gRPC status code mapping
    - Code generation for error handling utilities
    - Documentation generation
    - Type-safe error detail validation

    Usage Example:
      enum StreamErrorCode {
        REVISION_CONFLICT = 5 [(kurrent.rpc.error) = {
          status_code: FAILED_PRECONDITION,
          has_details: true
        }];
      }

    See individual field documentation for conventions and defaults.
    """

    DESCRIPTOR: _descriptor.Descriptor

    STATUS_CODE_FIELD_NUMBER: _builtins.int
    HAS_DETAILS_FIELD_NUMBER: _builtins.int
    status_code: _code_pb2.Code.ValueType
    """Maps the error to a standard gRPC status code for transport-level compatibility.
    This field is REQUIRED for every error annotation.

    Use standard gRPC status codes from `google.rpc.code`.

    Code generators use this to:
    - Map errors to gRPC status codes automatically
    - Generate HTTP status code mappings
    - Create transport-agnostic error handling
    """
    has_details: _builtins.bool
    """Indicates whether this error supports rich, typed detail messages.
    Defaults to false (simple message string only).
    The message type name must be derived from the enum name by convention.
    Mask: {EnumValue}ErrorDetails, {EnumValue}Error, {EnumValue}

    Examples:
      ACCESS_DENIED    -> "AccessDeniedErrorDetails", "AccessDeniedError" or "AccessDenied"
      SERVER_NOT_READY -> "ServerNotReadyErrorDetails", "ServerNotReadyError" or "ServerNotReady"

    Code generators use the message type name to:
    - Validate that the detail message matches the expected type
    - Generate type-safe error handling code
    - Create accurate documentation
    """
    def __init__(
        self,
        *,
        status_code: _code_pb2.Code.ValueType = ...,
        has_details: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["has_details", b"has_details", "status_code", b"status_code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ErrorMetadata: _TypeAlias = ErrorMetadata  # noqa: Y015

ERROR_FIELD_NUMBER: _builtins.int
error: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.EnumValueOptions, Global___ErrorMetadata]
"""Provides additional information about error conditions for automated
code generation and documentation.
"""
