# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kurrentdbclient/protos/kurrent/rpc/rpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kurrentdbclient/protos/kurrent/rpc/rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
from kurrentdbclient.protos.google.rpc import code_pb2 as kurrentdbclient_dot_protos_dot_google_dot_rpc_dot_code__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,kurrentdbclient/protos/kurrent/rpc/rpc.proto\x12\x0bkurrent.rpc\x1a google/protobuf/descriptor.proto\x1a,kurrentdbclient/protos/google/rpc/code.proto\"K\n\rErrorMetadata\x12%\n\x0bstatus_code\x18\x01 \x01(\x0e\x32\x10.google.rpc.Code\x12\x13\n\x0bhas_details\x18\x02 \x01(\x08:Q\n\x05\x65rror\x12!.google.protobuf.EnumValueOptions\x18\xd0\x86\x03 \x01(\x0b\x32\x1a.kurrent.rpc.ErrorMetadata\x88\x01\x01\x42\x0e\xaa\x02\x0bKurrent.Rpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kurrentdbclient.protos.kurrent.rpc.rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\013Kurrent.Rpc'
  _globals['_ERRORMETADATA']._serialized_start=141
  _globals['_ERRORMETADATA']._serialized_end=216
# @@protoc_insertion_point(module_scope)
